spark_lichtsteuerung:
    resource: "@SparkLichtsteuerungBundle/Controller/"
    type:     annotation
    prefix:   /

spark_spark_touch:
    resource: "@SparkSparkTouchBundle/Resources/config/routing.yml"
    prefix:   /

spark_olymp_rgb:
    resource: "@SparkOlympRGBBundle/Controller/"
    type:     annotation
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc