spark_web:
    resource: "@SparkWebBundle/Controller/"
    type:     annotation
    prefix:   /

spark_spark_touch:
    resource: "@SparkSparkTouchBundle/Resources/config/routing.yml"
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc